# core
alias ll="ls -al"
alias sed="gsed"
alias scrcpy="scrcpy"
alias rosetta="arch -x86_64"

# git
alias g="git"
alias ga="git add ."
alias gb="git branch"
alias gc="git checkout"
alias gl="git log"
alias gp="git push"
alias gs="git status"
alias gbc="git checkout -b"
alias gbl="git branch --list"
alias gcm="git commit -m"
alias gfo="git fetch origin"
alias gfu="git fetch upstream"
alias gpf="git push -f"
alias grc="git rebase --continue"
alias grm="git rebase main"
alias grho="git reset --hard origin/main"
alias grhu="git reset --hard upstream/main"
alias grmi="git rebase main --interactive"
alias guo="gfo && grho && gpf && gc main && grho && gc develop"

# npm
alias nr="npm run"
alias ns="npm start"
alias nrl="npm run lint"
alias nrt="npm run test"
alias nrtq="npm run test:quick --"
alias nrtu="npm run test:unit"
alias ncu="ncu -x eslint-config-spoke"
